DISTRO = "myowndisto"
DISTRO_NAME = "MARCOS"
DISTRO_VERSION = "1.0"

# Base OE-Core distro policy
require conf/distro/defaultsetup.conf


# System capabilities
DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED:append = " sysvinit"
DISTRO_FEATURES +=  "wayland x11 opengl"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"


# Override default distro features

DISTRO_FEATURES:append = " wifi bluetooth"

# Toolchain / packaging policy
TCLIBC = "glibc"
PACKAGE_CLASSES = "package_ipk"

IMAGE_INSTALL:append = " hello-kernel"
IMAGE_INSTALL:append = " char-device"
IMAGE_INSTALL:append = " gpio-interrupt"
IMAGE_INSTALL:append = " i2c-module"


# getting I2C
ENABLE_I2C = "1"
KERNEL_MODULE_AUTOLOAD:rpi += "i2c-dev i2c-bcm2708"
IMAGE_INSTALL:append = " i2c-tools "

# securing feature for read-only rootfs
IMAGE_FEATURES += "read-only-rootfs"