DISTRO = "myowndisto"
DISTRO_NAME = "MARCOS"
DISTRO_VERSION = "2.0"

include conf/distro/defaultsetup.conf

PACKAGE_CLASSES ?= "package_ipk" 
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES ?= "largefile opengl pcmcia usbhost wifi systemd"
